"""add notificacoes

Revision ID: 54a76494d2fd
Revises: eca0bee7451b
Create Date: 2026-08-04 13:40:44.682088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a76494d2fd'
down_revision = 'eca0bee7451b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('atividade_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('ATRIBUICAO', 'MENCAO', 'COMENTARIO', 'PRAZO_PROXIMO', name='notificacaotipo'), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
