"""initial schema

Revision ID: eca0bee7451b
Revises: 
Create Date: 2026-08-03 15:51:46.683605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca0bee7451b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PROFESSOR', 'ALUNO', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('arquivada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estagios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('is_conclusao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('estagio_id', sa.UUID(), nullable=False),
    sa.Column('criador_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_inicio_estagio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estagio_id'], ['estagios.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_membros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_gestor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'user_id', name='uq_grupo_membro')
    )
    op.create_table('anexos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atividade_id', sa.UUID(), nullable=False),
    sa.Column('nome_referencia', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade_historico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atividade_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('estagio_de_id', sa.UUID(), nullable=True),
    sa.Column('estagio_para_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['estagio_de_id'], ['estagios.id'], ),
    sa.ForeignKeyConstraint(['estagio_para_id'], ['estagios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade_responsaveis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atividade_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atividade_id', 'user_id', name='uq_atividade_responsavel')
    )
    op.create_table('checklist_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atividade_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atividade_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexo_versoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anexo_id', sa.UUID(), nullable=False),
    sa.Column('versao_numero', sa.Integer(), nullable=False),
    sa.Column('arquivo_path', sa.String(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anexo_id'], ['anexos.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexo_versoes')
    op.drop_table('comentarios')
    op.drop_table('checklist_itens')
    op.drop_table('atividade_responsaveis')
    op.drop_table('atividade_historico')
    op.drop_table('anexos')
    op.drop_table('grupo_membros')
    op.drop_table('atividades')
    op.drop_table('grupos')
    op.drop_table('estagios')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
